In [1]:
import pandas as pd

In [5]:
# Data Extraction
start_date = "2017-01-1"
end_date = "2022-06-01"
symbol = "SPY"
#data = yf.download(symbol, start=start_date, end=end_date)
df= pd.read_csv("../Dataset/data_historic_stock.csv")

# df = df[["Open", "High", "Low", "Close", "Volume"]]
#print(df['Ticker'].unique())
df.head()

  Ticker        Date    Open    High     Low   Close
0   ADBE  2023-12-06  608.06  608.53  594.49  595.70
1   ADBE  2023-12-05  596.77  602.74  591.17  602.22
2   ADBE  2023-12-04  604.91  608.29  596.21  604.56
3   ADBE  2023-12-01  609.24  615.20  603.18  612.47
4   ADBE  2023-11-30  620.00  621.48  605.07  611.01

In [7]:
df['Date'] = pd.to_datetime(df['Date'])

# Sort values by 'Ticker' and 'Date' in case it's not sorted already
df = df.sort_values(by=['Ticker', 'Date'])

df['Date'] = pd.to_datetime(df['Date'])
df['Close_Pct_Change'] = df.groupby('Ticker')['Close'].pct_change()

# Calculate the mean percentage change for each day
mean_pct_change = df.groupby('Date')['Close_Pct_Change'].mean().reset_index()

# Create a new DataFrame with only 'Date' and 'mean of % difference'
result_df = mean_pct_change[['Date', 'Close_Pct_Change']].rename(columns={'Close_Pct_Change': 'Mean_%_Difference'})

#print(result_df)
result_df.head()

        Date  Mean_%_Difference
0 2023-07-18                NaN
1 2023-07-19           0.001705
2 2023-07-20          -0.019591
3 2023-07-21           0.003940
4 2023-07-24          -0.002198